spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formula1B
    username: f1DB
    password: AlonsoEsDios
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update